In [267]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import math
import matplotlib.pyplot as plt

In [259]:
def generateXvector(X):
    """ Taking the original independent variables matrix and add a row of 1 which corresponds to x_0
    x -> feature
        Parameters:
          X:  independent variables matrix
        Return value: the matrix that contains all the values in the dataset, not include the outcomes variables.
        shape[0] rows
    """
    vectorX = np.c_[np.ones((X.shape[0], 1)), X]
    return vectorX

In [263]:
def weights_intilization(X):
    """ Generate an initial value of vector θ weights from the original independent variables matrix
         Parameters:
          X:  independent variables matrix
        Return value: a vector of theta filled with initial guess

    """
    theta = np.random.randn(X.shape[1]+1, 1)
    return theta

In [264]:
def sigmoid_function(X):
    """ Calculate the sigmoid value of the inputs
         Parameters:
          X:  values
        Return value: the sigmoid value
        make output 0,1 binary classification
    """
    return 1/(1+math.e**(-X))

In [284]:
def Logistics_Regression(X , y, learningrate, iterations):
    """ Find the Logistics regression model for the data set
         Parameters:
          X: independent variables matrix
          y: dependent variables matrix
          learningrate: learningrate of Gradient Descent
          iterations: the number of iterations
        Return value: the final theta vector and the plot of cost function
    """
    y_new = np.reshape(y, (len(y), 1))   
    cost_lst = []
    vectorX = generateXvector(X)
    theta = weights_intilization(X)
    m = len(X)
    # training
    for i in range(iterations):
        gradients = 2/m * vectorX.T.dot(sigmoid_function(vectorX.dot(theta)) - y_new)
        theta = theta - learningrate * gradients
        y_pred = sigmoid_function(vectorX.dot(theta))
        cost_value = - np.sum(np.dot(y_new.T,np.log(y_pred)+ np.dot((1-y_new).T,np.log(1-y_pred)))) /(len(y_pred))
        print(cost_value)
 #Calculate the loss for each training instance
        cost_lst.append(cost_value)
    return theta

In [228]:
cols=['Oldpeak','RestBP','Chol','Thal','AHD']

In [229]:
df=pd.read_csv('./heart.csv',usecols=cols)

In [230]:
df

     RestBP  Chol  Oldpeak        Thal  AHD
0       145   233      2.3       fixed   No
1       160   286      1.5      normal  Yes
2       120   229      2.6  reversable  Yes
3       130   250      3.5      normal   No
4       130   204      1.4      normal   No
..      ...   ...      ...         ...  ...
298     110   264      1.2  reversable  Yes
299     144   193      3.4  reversable  Yes
300     130   131      1.2  reversable  Yes
301     130   236      0.0      normal  Yes
302     138   175      0.0      normal   No

[303 rows x 5 columns]

In [231]:
df.dropna(inplace=True) # drop nulls

### Encoding Categorical Variables

In [232]:
df.AHD.replace({'Yes':1,'No':0},inplace=True)

In [233]:
df.head()

   RestBP  Chol  Oldpeak        Thal  AHD
0     145   233      2.3       fixed    0
1     160   286      1.5      normal    1
2     120   229      2.6  reversable    1
3     130   250      3.5      normal    0
4     130   204      1.4      normal    0

In [234]:
ordinal_mapping={'fixed': 0, 'normal': 1, 'reversable': 2}

In [235]:
df['Thal'].replace(ordinal_mapping,inplace=True)

In [236]:
df['Thal']

0      0
1      1
2      2
3      1
4      1
      ..
298    2
299    2
300    2
301    1
302    1
Name: Thal, Length: 301, dtype: int64

In [237]:
df.head()

   RestBP  Chol  Oldpeak  Thal  AHD
0     145   233      2.3     0    0
1     160   286      1.5     1    1
2     120   229      2.6     2    1
3     130   250      3.5     1    0
4     130   204      1.4     1    0

In [238]:
X=df.drop('AHD',axis=1)

In [239]:
X

     RestBP  Chol  Oldpeak  Thal
0       145   233      2.3     0
1       160   286      1.5     1
2       120   229      2.6     2
3       130   250      3.5     1
4       130   204      1.4     1
..      ...   ...      ...   ...
298     110   264      1.2     2
299     144   193      3.4     2
300     130   131      1.2     2
301     130   236      0.0     1
302     138   175      0.0     1

[301 rows x 4 columns]

In [240]:
y=np.array(df['AHD']).astype(int)

In [241]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [242]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size = 0.2, random_state = 0)

### LogisticsRegression function from SkLearn

In [243]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

In [244]:
predictions=classifier.predict(X_test)

In [245]:
accuracy_score(y_test,predictions)

0.7868852459016393

### LogisticsRegression from scratch

In [285]:
Logistics_Regression(X_train,y_train, 0.01, 1000)

<ipython-input-264-73a97f22efc6>:7: RuntimeWarning: overflow encountered in power
  return 1/(1+math.e**(-X))
<ipython-input-284-81c41a2fec59>:19: RuntimeWarning: divide by zero encountered in log
  cost_value = - np.sum(np.dot(y_new.T,np.log(y_pred)+ np.dot((1-y_new).T,np.log(1-y_pred)))) /(len(y_pred))

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
22.75218077158657
nan
80.93369119097783
nan
121.8231627673667
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
33.02981046365177
nan
98.40124930916299
nan
139.29072088555185
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
12.99482256731502
nan
66.96023904939285
nan
107.84971062578173
nan
148.7391822021706
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
424.53164152171865
126.97488162187116
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
16.88692229457008
nan
57.77664367338087
nan
98.66611524976975
nan
139.5555868261586
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
23.890653166152223
nan
64.78012480981177
nan
105.66959638620065
nan
146.5590679625895
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
578.7157573712982
nan
nan
nan
nan
nan
13.714316298728537
nan
54.61126754692849
nan
95.50073912331736
nan
136.39021069970622
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
26.30224985715058
nan
67.19172143461842
nan
108.0811930110073
nan
148.97066458739616
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
330.33021407405266
143.00000385719972
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
969.7444014618779
nan
32.90621932835405
nan
73.79569090474291
nan
114.6851624811318
nan
155.57463405752065
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
7.723822465801006
nan
76.01980825119477
nan
116.90927982758367
nan
157.79875140397252
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
6.914016266233676
nan
53.86488863687247
nan
94.75436021326135
nan
135.6438317896502
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
25.5558718821674
nan
66.44534345873777
nan
107.33481503512664
nan
148.2242866115155
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
353.63089781700677
nan
nan
nan
nan
nan
nan
nan
1092.7086467815302
nan
31.752590773636168
nan
72.64206235002504
nan
113.53153392641391
nan
154.42100550280279
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
8.2641984925683
nan
91.91375472379436
nan
132.8032263001832
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
22.715266397391115
nan
63.60473797407213
nan
104.494209550461
nan
145.38368112684986
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
642.0813591480658
nan
27.33145027476974
nan
68.22092185116027
nan
109.11039342754914
nan
149.999865003938
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
165.63934212560315
77.6574608298093
nan
118.54693240619817
nan
159.43640398258702
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
8.459025829102028
nan
49.369182883781235
nan
90.25865446017012
nan
131.14812603655898
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
21.060166133779504
nan
61.94963771061354
nan
102.83910928700242
nan
143.7285808633913
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
826.0618975872278
nan
33.63205912858128
nan
74.52153070497016
nan
115.41100228135903
nan
156.3004738577479
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
5.591198704091009
nan
59.07574223157391
nan
99.96521380796278
nan
140.85468538435168
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
30.766530443604868
nan
71.65600201999382
nan
112.54547359638269
nan
153.4349451727716
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
26.619641757606995
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
16.947539976726897
nan
57.83703887945603
nan
98.72651045584489
nan
139.61598203223375
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
29.528013684138156
nan
70.41748526052766
nan
111.30695683691653
nan
152.1964284133054
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
46.736404978192496
nan
nan
nan
nan
nan
nan
nan
nan
14.787057624849536
nan
55.67659340005248
nan
96.56606497644134
nan
137.4555365528302
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
27.367576561176538
nan
68.25704813756674
nan
109.1465197139556
nan
150.03599129034447
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
109.16827991791412
50.30586482995079
nan
91.19533640633968
nan
132.08480798272856
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
21.99684807983882
nan
62.88631965627317
nan
103.77579123266204
nan
144.66526280905092
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
663.2393803317083
nan
34.54012353058595
nan
75.42959510697483
nan
116.31906668336369
nan
157.20853825975254
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
6.264210314199306
nan
50.4416761788364
nan
91.3311477552253
nan
132.22061933161416
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
22.132659429033538
nan
63.02213113314989
nan
103.91160270953876
nan
144.80107428592765
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
630.5454918799646
nan
27.434527581782884
nan
68.32399915832687
nan
109.21347073471576
nan
150.1029423111046
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
115.25912814054372
15.579358186459924
nan
56.468839746784404
nan
97.35831132317327
nan
138.24778289956217
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
28.159822025060368
nan
69.04929360144946
nan
109.93876517783833
nan
150.82823675422722
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
40.62066144179131
nan
nan
nan
nan
nan
nan
27.666918169528504
nan
68.55638974591737
nan
109.44586132230624
nan
150.33533289869513
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
42.792678186285244
nan
nan
5.936660929312736
nan
49.34521261934302
nan
90.2346841957319
nan
131.1241557721208
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
21.036195869312376
nan
61.92566745670444
nan
102.8151390330933
nan
143.7046106094822
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
736.5427783445672
nan
33.600858721079895
nan
74.49033029746876
nan
115.37980187385764
nan
156.26927345024652
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
5.3838179700753885
nan
55.83419857659785
nan
96.72367015298671
nan
137.6131417293756
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
27.525181430837808
nan
68.41465300778744
nan
109.30412458417632
nan
150.19359616056516
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
85.47239316321142
nan
nan
16.413818344337148
nan
57.3033650168686
nan
98.19283659325747
nan
139.08230816964635
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
28.994340319727954
nan
69.88381189611825
nan
110.77328347250713
nan
151.662755048896
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
21.630051964409464
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
24.69983866739273
nan
65.58931024445964
nan
106.47878182084851
nan
147.3682533972374
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
256.8458028256345
nan
992.5476813336056
nan
31.28762868511047
nan
72.17710026149943
nan
113.06657183788829
nan
153.9560434142772
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
4.905490623487044
nan
98.7511120856745
nan
139.64058366206336
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
29.552599573858856
nan
70.44207115026968
nan
111.33154272665857
nan
152.22101430304744
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
18.8894177289986
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
6.399955435502004
nan
126.29752117415734
nan
167.18699275054624
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
16.20960279012865
nan
57.123282967569246
nan
98.01275454395812
nan
138.90222612034697
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
28.814257232405843
nan
69.7037288092295
nan
110.59320038561836
nan
151.48267196200723
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
32.55970507297802
nan
nan
nan
nan
nan
nan
nan
nan
4.558483270314659
nan
81.36133490270215
nan
122.25080647909105
nan
163.1402780554799
nan
nan
nan
nan
nan
nan
nan

array([[-2.2174378 ],
       [ 0.27671854],
       [ 0.42452141],
       [ 4.10453527],
       [ 0.60901947]])